# Generated by Django 2.2.9 on 2020-02-02 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(choices=[('Żagań', 'Żagań'), ('Kielce', 'Kielce')], max_length=1)),
            ],
        ),
    ]
