# Generated by Django 2.2.9 on 2020-01-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200128_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='id_user',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
