# Generated by Django 2.2.9 on 2020-02-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_place'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='city',
            field=models.CharField(choices=[('Żagań', 'Żagań'), ('Kielce', 'Kielce')], max_length=20),
        ),
    ]
