# Generated by Django 2.2.9 on 2020-01-29 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id_user',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
